file_format: "1"
id: cardinal
name: Cardinal
type: shield
url: https://github.com/LucasKniska/zmk-config-cardinal1
requires: [Nice!nano]
features:
  - keys
siblings:
  - cardinal1_left
  - cardinal1_right